version: '3.5'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: docker-next
    volumes:
      - ./app:/app
      - /app/node_modules
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: docker-api
    volumes:
      - ./api:/api
      - /api/node_modules
  web:
    image: nginx:alpine
    container_name: docker-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
      - api